spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${APP_USER}
spring.datasource.password=${APP_USER_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${RESOURCE_SERVER_JWK_SET_URI}

