spring.application.name=order-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${APP_USER}
spring.datasource.password=${APP_USER_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
