spring.application.name=order-service
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/${DB_DATABASE}
spring.datasource.username=${APP_USER}
spring.datasource.password=${APP_USER_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

